import { BankType } from 'lib/transformer/transformBanks';

const banks: Array<BankType> = [
  {
    name: 'motor:loan_banks:KRUNGSRI',
    logo: '/images/banks/bank_4.svg,',
    isRecommended: false,
    isActive: true,
    flatRate: '3.09',
    effective: '5.57',
    maxLoan: '5M',
    maxTerm: 84,
    ncbCheck: true,
    shortName: 'KRUNGSRI',
  },
  {
    name: 'motor:loan_banks:KBANK',
    logo: '/images/banks/bank_3.svg,',
    flatRate: '4.06',
    effective: '7.31',
    maxLoan: '5M',
    maxTerm: 72,
    ncbCheck: true,
    isRecommended: false,
    isActive: true,
    shortName: 'KBANK',
  },
  {
    name: 'motor:loan_banks:SCB',
    isRecommended: false,
    logo: '/images/banks/bank_1.svg,',
    isActive: true,
    flatRate: '5.05',
    effective: '9.09',
    maxLoan: '5M',
    maxTerm: 84,
    ncbCheck: true,
    shortName: 'SCB',
  },
  {
    name: 'motor:loan_banks:KKP',
    logo: '/images/banks/bank_2.svg,',
    isRecommended: false,
    isActive: true,
    flatRate: '6.65',
    effective: '11.97',
    maxLoan: '5M',
    maxTerm: 84,
    ncbCheck: true,
    shortName: 'KKP',
  },
  {
    name: 'motor:loan_banks:TISCO',
    logo: '/images/banks/bank_5.svg,',
    isRecommended: false,
    isActive: true,
    flatRate: '5.88',
    effective: '10.58',
    maxLoan: '10M',
    maxTerm: 72,
    ncbCheck: true,
    shortName: 'TISCO',
  },
  {
    name: 'motor:loan_banks:ASN',
    logo: '/images/banks/bank_6.svg,',
    isRecommended: false,
    isActive: true,
    flatRate: '9.48',
    effective: '17.06',
    maxLoan: '300K',
    maxTerm: 48,
    ncbCheck: false,
    shortName: 'ASN',
  },
  {
    name: 'motor:loan_banks:SOMWANG',
    logo: '/images/banks/bank_7.svg,',
    isRecommended: false,
    isActive: false,
    flatRate: '5.88',
    effective: '10.58',
    maxLoan: '10M',
    maxTerm: 72,
    ncbCheck: false,
    eligibleText: 'You are not eligible for this bank',
    shortName: 'SOMWANG',
  },
  {
    name: 'motor:loan_banks:CARFINN',
    logo: '/images/banks/bank_8.svg,',
    isRecommended: false,
    isActive: false,
    flatRate: '3.6',
    effective: '6.48',
    maxLoan: '500K',
    maxTerm: 72,
    ncbCheck: false,
    eligibleText: 'You are not eligible for this bank',
    shortName: 'CARFINN',
  },
];

export default banks;

export const provincesASNNotAccept = [
  '570000',
  '580000',
  '630000',
  '430000',
  '270000',
  '930000',
  '830000',
  '910000',
  '940000',
  '960000',
  '920000',
];

export const provincesCarFinnAccept = [
  '100000',
  '130000',
  '120000',
  '730000',
  '110000',
  '740000',
  '210000',
  '200000',
  '760000',
  '700000',
  '160000',
  '750000',
  '170000',
  '720000',
  '140000',
  '150000',
  '300000',
  '240000',
  '710000',
  '180000',
  '250000',
  '610000',
  '270000',
];

export const carBrandsKKPAccept = [
  'Toyota',
  'Honda',
  'Isuzu',
  'Suzuki',
  'Mazda',
  'Mitsubishi',
  'Nissan',
  'Ford',
  'Hyundai',
  'BMW',
  'Mercedes-Benz',
  'MG',
  'Audi',
];

export const carBrandsKrungsriAccept = [
  'BMW',
  'Chevrolet',
  'Ford',
  'Honda',
  'Hyundai',
  'Isuzu',
  'Kia',
  'Lexus',
  'Mazda',
  'Mercedes-Benz',
  'MG',
  'Mitsubishi',
  'Nissan',
  'Proton',
  'Subaru',
  'TR',
  'Suzuki',
  'Toyota',
  'Volvo',
];
